let text = "surya Prakash";
//let length = text.length;
//console.log(length);
//console.log(text.slice(2,5));
//console.log(text.substring(6,13));
//console.log(text.substr(6,7));
//console.log(text.replace('surya','suria'));
//console.log(text.toUpperCase());
let text1 = '5';
//console.log(text1.toLowerCase());
//console.log(text.concat(text1));
//console.log(text1.trim());
//console.log(text1.padStart(5,"x"));
//console.log(text1.padEnd(4,"x"));
//console.log(text.charAt(7));
console.log(text.charCodeAt(4));